european_energy:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_DATASET') }}"
      location: EU
      threads: 4
