from google.cloud import bigquery

ACTUAL_LOAD_SCHEMA = (
    bigquery.SchemaField("source_object_name", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("document_mrid", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("document_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("revision_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("document_created_at", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("process_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("time_series_mrid", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("business_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("object_aggregation", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("out_bidding_zone", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("quantity_unit", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("curve_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("period_start", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("period_end", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("resolution", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("position", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("point_timestamp", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("quantity", "NUMERIC", mode="REQUIRED"),
)


ACTUAL_GENERATION_SCHEMA = (
    bigquery.SchemaField("source_object_name", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("document_mrid", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("document_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("revision_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("document_created_at", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("process_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("time_series_mrid", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("business_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("object_aggregation", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("in_bidding_zone", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("out_bidding_zone", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("quantity_unit", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("curve_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("psr_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("period_start", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("period_end", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("resolution", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("position", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("point_timestamp", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("quantity", "NUMERIC", mode="REQUIRED"),
)


DAY_AHEAD_PRICES_SCHEMA = (
    bigquery.SchemaField("source_object_name", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("document_mrid", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("document_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("revision_number", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("document_created_at", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("time_series_mrid", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("auction_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("business_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("in_domain", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("out_domain", "STRING", mode="REQUIRED"),
    bigquery.SchemaField(
        "contract_market_agreement_type",
        "STRING",
        mode="REQUIRED",
    ),
    bigquery.SchemaField("currency_unit", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("price_unit", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("curve_type", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("period_start", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("period_end", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("resolution", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("position", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("point_timestamp", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("price_amount", "NUMERIC", mode="REQUIRED"),
)
